spring:
  application:
    name: spring-cloud-provider-01
  profiles:
    active: local
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
    #配置數據源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pds2_longfor
    username: root
    password: 123456
  #配置日志
  logging:
    pattern:
      console: level-%level %msg%n
    #日志的显示级别
    level:
      root: info
      org.hibernate: info
      # 在show-sql为true时显示sql中的动态参数
      org.hibernate,type,desciptor.sql.BasicBinder: trace
      org.hibernate,type,desciptor.sql.BasicExtractor: trace
      com.abc.msg: debug

server:
  port: 8081

